puts "I can do all the maths!"
puts "Give me any two numbers, and I will do all the math things on them."
puts ""
puts "enter any number =>"
firstNum = gets.chomp!.to_f
puts ""
puts "enter another number=>"
secondNum = gets.chomp!.to_f
puts ""
puts "Prepare to be amazed. Here ya go!"
puts ""
puts "#{firstNum} + #{secondNum} = #{ firstNum + secondNum}"
puts "Addition "
puts ""
puts "#{firstNum} - #{secondNum} = #{ firstNum - secondNum}"
puts "Subtraction "
puts ""
puts "#{firstNum} x #{secondNum} = #{ firstNum * secondNum}"
puts "Multiplication "
puts ""
puts "#{firstNum} / #{secondNum} = #{ firstNum / secondNum}"
puts "Division "
puts ""
puts "#{firstNum} % #{secondNum} = #{ firstNum % secondNum}"
puts "Modulus "
puts ""
puts "#{firstNum} ** #{secondNum} = #{ firstNum ** secondNum}"
puts "Exponent "
puts ""